name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: android-actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Debug: List Build Outputs
        if: always()
        run: |
          echo "Listing contents of app/build/outputs/apk/..."
          find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/**/*.apk
          if-no-files-found: error
          
